# Easy programming for everybody

http://tullo.ch/articles/python-vs-julia/

In [5]:
import numpy as np
import time

## 1) Summing a series 

In [67]:
def one_over_n(n):
    aux = 0.
    for i in range(1,n+1):
        aux += 1./i          
    return aux

In [74]:
t0 = time.time()
aux = one_over_n(1000000)
print("time needed:", time.time() - t0)
print(aux)

('time needed:', 0.12250494956970215)
14.3927267229


## 2) Controlling outliers ( or clipping gradients)

In [204]:
def clip( x, a=0 , b= 1 ):
    for i in range(len(x)):
        if x[i] < a:
            x[i] = a
        elif x[i] > b:
            x[i] = b
    return x

In [205]:
x = np.random.randn(10**7)

In [207]:
t0 = time.time()
x = clip(x,0,1)
print(time.time() - t0)

5.8660948276519775


In [174]:
x[1:10]

array([ 0.        ,  0.        ,  0.71956263,  0.        ,  0.72998114,
        1.        ,  1.        ,  0.402447  ,  0.        ])

### Yeah but I not as noob, I would never do that

In [191]:
x = np.random.randn(10**7)

In [192]:
t0 = time.time()
x[x>1] = 1.
x[x<0] = 0.
print(time.time() - t0)

0.1246480941772461


In [193]:
x

array([ 0.68872952,  1.        ,  0.75399274, ...,  1.        ,
        0.        ,  0.        ])

### Maybe in float32 this is faster

In [222]:
x = np.array(np.random.randn(10**7), dtype="float32")

In [223]:
t0 = time.time()
x[x>1] = 1.
x[x<0] = 0.
print(time.time() - t0)

0.11884403228759766


## 3) Computing a quantity depending on a "custom criteria"

In [224]:
def compute_taxes(salary):
    if salary < 18000:
        return salary * 0.2
    elif  18000 < salary < 25000:
        return salary * 0.3
    elif   25000 < salary < 70000:
        return salary * 0.4
    else:
        return salary * 0.5

In [63]:
np.random.randint(18000, 80000, 10)

array([47600, 26032, 61791, 47482, 75478, 27669, 55756, 28307, 74294, 19458])

In [225]:
salaries = np.array(np.random.randint(18.000, 100000, 10**6), "int64")
t0 = time.time()
taxes = [compute_taxes(x) for x in salaries ]
print(time.time() - t0)

2.1521639823913574


## 4) L2 norm

In [46]:
len_ = 1000000;
x = np.random.rand(len_);
y = np.random.rand(len_);

In [35]:
t0 = time.time()
(x - y)**2/x.shape[0]
print(time.time() - t0)

0.0132551193237


In [51]:
def l2_squared(x,y):
    norm = 0.
    for i in range(x.shape[0]):
        norm = norm + (x[i] - y[i])**2
    return norm/x.shape[0]

In [52]:
t0 = time.time()
l2_squared(x,y)
print(time.time() - t0)

0.620918035507


In [58]:
t0 = time.time()
np.linalg.norm(x-y,2)**2
print(time.time() - t0)

0.00598287582397
