# Easy programming for everybody

http://tullo.ch/articles/python-vs-julia/

In [1]:
import numpy as np
import time

## 1) Summing a series 

In [32]:
def one_over_n(n):
    aux = 0.
    for i in range(1,n+1):
        aux += 1./i          
    return aux

In [33]:
t0 = time.time()
aux = one_over_n(1000000)
print("time needed:", time.time() - t0)
print(aux)

time needed: 0.1349780559539795
14.392726722864989


## 2) Controlling outliers ( or clipping gradients)

In [4]:
def clip( x, a=0 , b= 1 ):
    for i in range(len(x)):
        if x[i] < a:
            x[i] = a
        elif x[i] > b:
            x[i] = b
    return x

In [5]:
x = np.random.randn(10**7)

In [6]:
t0 = time.time()
x = clip(x,0,1)
print(time.time() - t0)

5.430553913116455


In [7]:
x[1:10]

array([ 0.91234391,  0.58787793,  1.        ,  0.        ,  0.        ,
        0.35272126,  0.        ,  0.86482806,  1.        ])

### Yeah but I not as noob, I would never do that

In [27]:
x = np.random.randn(10**7)

In [29]:
x>1

array([False, False, False, ..., False, False, False], dtype=bool)

In [25]:
t0 = time.time()
x[x>1] = 1.
x[x<0] = 0.
print(time.time() - t0)

0.02113795280456543


In [10]:
x = np.array(np.random.randn(10**7), dtype="Float32")

/Users/david/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  if __name__ == '__main__':


In [11]:
t0 = time.time()
x[x>1] = 1.
x[x<0] = 0.
print(time.time() - t0)

0.11089897155761719


### Maybe in float32 this is faster

In [222]:
x = np.array(np.random.randn(10**7), dtype="float32")

In [223]:
t0 = time.time()
x[x>1] = 1.
x[x<0] = 0.
print(time.time() - t0)

0.11884403228759766


## 3) Computing a quantity depending on a "custom criteria"

In [24]:
def compute_taxes(salary):
    if salary < 18000:
        return salary * 0.2
    elif  18000 < salary < 25000:
        return salary * 0.3
    elif   25000 < salary < 70000:
        return salary * 0.4
    else:
        return salary * 0.5

In [25]:
np.random.randint(18000, 80000, 10)

array([35805, 66776, 39363, 64825, 59098, 25562, 18514, 27533, 36334, 60297])

In [26]:
salaries = np.array(np.random.randint(18.000, 100000, 10**6), "int64")
t0 = time.time()
taxes = [compute_taxes(x) for x in salaries ]
print(time.time() - t0)

2.338346004486084


## 4) L2 norm

In [27]:
len_ = 1000000;
x = np.random.rand(len_);
y = np.random.rand(len_);

In [28]:
t0 = time.time()
(x - y)**2/x.shape[0]
print(time.time() - t0)

0.03705000877380371


In [51]:
def l2_squared(x,y):
    norm = 0.
    for i in range(x.shape[0]):
        norm = norm + (x[i] - y[i])**2
    return norm/x.shape[0]

In [52]:
t0 = time.time()
l2_squared(x,y)
print(time.time() - t0)

0.620918035507


In [58]:
t0 = time.time()
np.linalg.norm(x-y,2)**2
print(time.time() - t0)

0.00598287582397
