## Julia basics

- https://learnxinyminutes.com/docs/julia/

### Numeric Types


#### Real numbers

In [40]:
typeof(2)

Int64

In [41]:
typeof(2.)

Float64

In [42]:
typeof(Float64)

DataType

In [43]:
typeof(AbstractFloat)

DataType

In [44]:
println("\n\nAbout Floats:")

println("\t",supertype(Float64))
println("\t",supertype(AbstractFloat))
println("\t",supertype(Real))
println("\t",supertype(Number))

println("\n\nAbout integers:")

println("\t",supertype(Int64))
println("\t",supertype(Signed))
println("\t",supertype(Integer))
println("\t",supertype(Real))
println("\t",supertype(Number))



About Floats:
	AbstractFloat
	Real
	Number
	Any


About integers:
	Signed
	Integer
	Real
	Number
	Any


In [45]:
a = [1,2,3,4,5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [67]:
length(a)

6

In [73]:
x1 = Nullable{Int64}(1)

Nullable{Int64}(1)

## Arrays

Every Array has the form ```Array{T,ndim}``` 

- ```T``` corresponds to a type 
- ndim the dimension of the array.

#### Some functions for arrays

- ```size``` returns the size of the array which is a tuple with the information about the shape of the array.
- ```length``` returns the total number of elements in the array

In [47]:
a = [x for x in 1:1000];

In [48]:
typeof(a)

Array{Int64,1}

In [49]:
a[1:4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [50]:
size(a)

(1000,)

In [51]:
length(a)

1000

#### Defining arrays by stating its elements

We can define arrays with the elements we want.


In [52]:
a = Array([1,2,3,4]);
b = Array([1 2 3 4]);

In [53]:
size(a), size(b)

((4,),(1,4))

In [54]:
words = ["house", "car", "dog"]

3-element Array{String,1}:
 "house"
 "car"  
 "dog"  

#### Basic functions for modifying arrays


- ```push!``` allow us to add an element at the end of the array
- ```append!``` allow us to add all the elements of a collection at the end of the array

In [62]:
a = [1, 2]

2-element Array{Int64,1}:
 1
 2

In [63]:
push!(a, 0)

3-element Array{Int64,1}:
 1
 2
 0

In [64]:
a

3-element Array{Int64,1}:
 1
 2
 0

In [65]:
append!(a,[2,3,4])

6-element Array{Int64,1}:
 1
 2
 0
 2
 3
 4

### Matrices and Vectors 

Matrices and Vectors are just Arrays with different dimensions. 


In [138]:
v = Vector([1,2,3]);

In [139]:
typeof(v)

Array{Int64,1}

In [125]:
Array([1 2 3 4])

1×4 Array{Int64,2}:
 1  2  3  4

In [120]:
M = Matrix([1 2 3 4; 5 6 7 8]);

In [141]:
M

2×4 Array{Int64,2}:
 1  2  3  4
 5  6  7  8

In [142]:
typeof(M)

Array{Int64,2}

#### Initialize arrays with values

- ```zeros``` generates an array with 0 values
- ```ones```  generates  an array with 1 values
- ```rand``` generates an array with numbers sampled from a uniform distribution in the interval [0,1]
- ```randn``` generates an array with numbers sampled from a Gaussian distribution with mean 0 and std 1

In [163]:
v = zeros(2)

2-element Array{Float64,1}:
 0.0
 0.0

In [165]:
ones(2)

2-element Array{Float64,1}:
 1.0
 1.0

In [160]:
Array{Float32}(zeros(2,5))

2×5 Array{Float32,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [180]:
rand(3)

3-element Array{Float64,1}:
 0.220978
 0.932801
 0.245316

In [190]:
randn(3)

3-element Array{Float64,1}:
 -1.03485 
 -1.59043 
 -0.110985